/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Carrito.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cart.geometry}
        material={materials["Material.001"]}
        position={[-0.998, 1.24, 0]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.002"]}
          position={[0.09, 1.421, -2.179]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.07, 1, 0.07]}
        />
        <group
          position={[1.093, -1.006, 0.789]}
          rotation={[-2.944, 0, -Math.PI / 2]}
          scale={0.8}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus_2.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus_3.geometry}
            material={materials["Material.005"]}
          />
        </group>
        <group
          position={[1.093, -1.006, -0.771]}
          rotation={[-2.944, 0, -Math.PI / 2]}
          scale={0.8}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus_2.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus_3.geometry}
            material={materials["Material.005"]}
          />
        </group>
        <group
          position={[-1.107, -1.006, -0.771]}
          rotation={[-2.944, 0, -Math.PI / 2]}
          scale={0.8}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus_2.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus_3.geometry}
            material={materials["Material.005"]}
          />
        </group>
        <group
          position={[-1.107, -1.006, 0.779]}
          rotation={[-2.944, 0, -Math.PI / 2]}
          scale={0.8}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus_2.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus_3.geometry}
            material={materials["Material.005"]}
          />
        </group>
      </mesh>
    </group>
  );
}

useGLTF.preload("/Carrito.gltf");

// function Side(){
//     return{
//         <div class="w-full flex items-center justify-center h-full text-4xl">
//         </div>
//     };
// }

export default Side;
